# Generated by Django 4.2.7 on 2024-02-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hodApp', '0003_alter_course_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='Course_id',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='session_year_id',
        ),
    ]
