# Generated by Django 4.2.7 on 2024-02-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hodApp', '0004_remove_staff_course_id_remove_staff_session_year_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
