# Generated by Django 4.2.7 on 2024-02-15 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hodApp', '0006_subject'),
        ('staffApp', '0005_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hodApp.course')),
                ('session_year', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hodApp.session_year')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hodApp.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_status', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendace', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='staffApp.attendace')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='hodApp.student')),
            ],
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
