# Generated by Django 4.2.7 on 2024-02-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffApp', '0006_attendace_attendance_report_delete_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance_report',
            name='leave_status',
        ),
        migrations.AddField(
            model_name='attendance_report',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
